import { type Content } from "../../types";

export const content: Content = {
  sun: [
  "Did you know that the sun is a star, just like the countless points of light sparkling in the night sky? In fact, it is relatively small compared to some of the other stars in the Milky Way. But it’s still the object our little planetary family— the solar system—whirls around, and its warmth and light make Earth a place where life can exist.",
  "The sun’s power comes from reactions unfolding deep within its core—here, the superheated matter is joined together, under immense temperatures and pressures. This process releases energy, which works its way out from the center to create the blazing hot, glowing ball that travels across the sky. The surface of the sun is unlike any other place in the solar system. It has been bubbling and blazing away every second for billions of years, beaming with incredible amounts of heat and light.",
  "Astronomers call the sun’s surface the photosphere, and it has a temperature of about 5,400°C. Sometimes, magnetic fields emerging from inside the sun reduce the amount of heat reaching parts of the surface. This creates cooler, darker patches of the photosphere, which we call sunspots. Larger sunspots usually have two parts to them—a dark heart, called an umbra, and a lighter border known as a penumbra. Sunspots can last many months, or they can disappear in just a few days.",
  "Sometimes, the shadow of the moon sweeps across the globe of the Earth. When this happens, anyone standing where the darker, central part of this shadow falls will experience a total solar eclipse. A total solar eclipse usually happens at least once every couple of years. During these spine-tingling events, the daylight slowly begins to fade to twilight. The air cools, and animals often behave as if they’re preparing for the evening.",
  "Soon after, a strange, silvery light falls on the landscape, and for a few moments everything gets dark, as the sun is entirely blocked by the black disk of the moon—this event is known as totality. As the core of the moon’s shadow moves away, totality ends and the sun’s light gradually returns.",
  ],
  mercury: [
  "At 4,879 km across, Mercury is the smallest planet in the solar system. It is named after the quick-footed messenger of the Roman gods, which is fitting since it races around the sun. Mercury is the closest planet to the sun, and its surface temperature can reach a blistering 430 degreed Celsius during the day. But because the planet has no atmosphere to retain that heat, nighttime temperatures on the surface can drop to minus 180 degrees Celsius.",
  "Its rocky crust shows the scars of asteroid and comet impacts, with almost its entire globe covered in craters. With the Caloris Basin being the biggest one, and it is larger than the size of France. Yet Mercury holds surprises too. In its polar regions, there are places—at the bottom of deep craters—that the blazing sunlight cannot reach. There might be water ice lurking in these tucked-away shaded spots.",
  "Its rocky crust shows the scars of asteroid and comet impacts, with almost its entire globe covered in craters. With the Caloris Basin being the biggest one, and it is larger than the size of France. Yet Mercury holds surprises too. In its polar regions, there are places—at the bottom of deep craters—that the blazing sunlight cannot reach. There might be water ice lurking in these tucked-away shaded spots.",
  "While there are large areas of smooth terrain, there are also cliffs, some hundreds of miles long and soaring up to a mile high. They rose as the planet's interior cooled and contracted over the billions of years since Mercury formed.",
  "As the inner planets, Mercury and Venus, whirl around the sun, they sometimes swoop in front of its face, from the perspective of Earth. These events are quite rare, and they’re called transits. The last transit of Mercury occurred back in 2019 and the next one will happen in the year 2032.",
  ],
  venus: [
    "Venus is the second brightest natural object in our night sky, after the moon. And is named after the Roman goddess of love. Even though it can float up to 261 million km away from Earth, Venus is still one of our closest planetary neighbors. The two planets are almost the same size, so they are sometimes called twins, but their stories are very different",
    "Venus is a world of many mysteries. Perhaps the most intriguing of them all is its barren, volcanic surface. Most of the planet is covered in enormous expanses of solidified lava. Ancient volcanoes rise up all over this bleak landscape, where a soft breeze stirs through the suffocating, hazy sky. One of the tallest volcanoes on Venus standing at 9 km high is named Maat Mons, after the Egyptian goddess of truth, Ma’at.",
    "About 500 million years ago, vast areas of Venus’s globe were swamped by a series of spectacular lava eruptions.  A few Venusian volcanoes may even be oozing lava today, but to find out for sure we’ll likely have to send probes back to the planet for a closer look.",
    "About 500 million years ago, vast areas of Venus’s globe were swamped by a series of spectacular lava eruptions.  A few Venusian volcanoes may even be oozing lava today, but to find out for sure we’ll likely have to send probes back to the planet for a closer look.",
    "Some scientists think that in the distant past, Venus had oceans of liquid water. These, however, have long since disappeared, and today all that remains is a volcanic landscape blanketed by thick clouds. What little we do know about the surface of Venus has come largely from the handful of space probes that have visited the planet. Some of these actually traveled down to the surface, where they experienced roasting temperatures of 460°C and crushing pressure from the toxic atmosphere.",
  ],
  earth: [
    "Our home planet Earth is a rocky, terrestrial planet. It has a solid and active surface with mountains, valleys, canyons, plains and so much more. Earth is special because it is an ocean planet. Water covers 70% of Earth's surface.",
    "Our atmosphere is made mostly of nitrogen and has plenty of oxygen for us to breathe. The atmosphere also protects us from incoming meteoroids, most of which break up in our atmosphere before they can strike the surface as meteorites. Earth's atmosphere is also the right thickness to keep the planet warm so living things like us can be here. It’s the only planet in our solar system we know of that supports life. It is mostly nitrogen, and it has plenty of oxygen for us to breathe.",
    "When we look up on a clear day, the sky glows a vibrant shade of blue. This is because the gases in the air scatter the bluer colors in the sunlight. When night falls, we can see another effect of the atmosphere: the gentle twinkling of the stars. This flickering happens because the moving air above us briefly distorts the path starlight takes to reach our eyes.",
    "Since we live here, you might think we know all there is to know about Earth. Not at all, actually! We have a lot we can learn about our home planet. Right now, there are many satellites orbiting Earth taking pictures and measurements. This is how we can learn more about weather, oceans, soil, climate change, and many other important topics.",
  ],
  mars: [
    "As we travel away from the sun, we cross the path of a world that humans may one day visit: Mars. For centuries, humans have looked toward this little world and imagined what wonders might lie there. Today, we know more about the “Red Planet” than ever before. We now know this is a planet covered in windswept plains, and scarred by vast canyons and enormous volcanic peaks. But the rocks and valleys of Mars also tell us that it wasn’t always so desolate and dusty. Could life once have existed here?",
    "When astronauts travel to Mars in the future, one of the most spectacular features they’ll see will be the Valles Marineris, or Mariner Valley. This immense canyon is a deep, roughly straight, gouge in the Martian surface that stretches an astonishing 2,200 km across the planet— longer than the entire length of Italy! Even today, the great mystery of the Valles Marineris is how it formed. Scientists have several ideas. For example, some believe the Martian crust split and a wide swathe slumped downward. The walls of the Valles Marineris drop 10 km in some places. Earth’s Grand Canyon looks tiny in comparison!",
    "When it comes to spectacular volcanoes, Mars takes the top spot. The mighty Olympus Mons is a shield volcano, which means it has a very broad base, with gently sloping sides. It’s much larger than any volcano on Earth. From its base to its peak, it gradually rises 21.9 km into the Martian sky, while its sides span about 640 km—it would take a jet airliner more than 40 minutes to fly across it. It is thought that Olympus Mons formed about 3.6 billion years ago, when huge amounts of lava oozed from inside the Red Planet.",
    "Dust devils—spinning vortexes of air like little tornadoes—have whipped over the ground, leaving trails that record their path. Several spacecraft have caught these whirlwinds in the act of flitting across the Red Planet. We now know there are other dusty phenomena in Mars’s skies, too: enormous dust storms occasionally stir within the planet’s atmosphere, enshrouding its globe in a murky, brown haze.",
    "If you could somehow walk safely across Mars today, you’d probably only hear the sound of a soft breeze stirring across the landscape, or the occasional flurry of an enormous dust storm. Billions of years ago, however, you may have also been able to listen to the crashing of waves and the roar of a river carving its way through the Martian rock.",
    "We think this because scientists have found clues, all over Mars, revealing how its surface was sculpted by large amounts of liquid water. Orbiting spacecraft have captured pictures of dried-up river valleys and lakes, while on the ground, rovers have found rocks and minerals that must have formed in a watery environment.",
    "Mars has two moons, named Phobos and Deimos. At roughly 23 km in diameter, Phobos is the larger of the two—Deimos is about 12 km across. Scientists are not sure where these moons came from. They could be space rocks that were captured by Mars’s gravity, or debris from a gigantic asteroid impact on the Martian surface long ago.",
    "The moons are oddly shaped and lumpy—this is because they aren’t massive enough for their own gravity to squash them into a ball, like other, larger moons in the solar system. As it orbits around Mars, Phobos is, very slowly, moving toward the planet. In just over 30 million years, it may even fall onto the Martian surface. Imagine seeing that!",
  ],
  jupiter: [
    "Jupiter is the largest planet in our solar system—so big that it could fit just over 11 Earths across its face. This tremendous size means that, despite it being far away from our planet, we can sometimes see it in the night sky as a shining point of light.",
    "Jupiter’s atmosphere is mostly made up of hydrogen and helium, but it also contains other gases like smelly ammonia. If you could fly above Jupiter and look down on its clouds, you’d notice huge swirls and pastel- colored ripples that stretch into the distance as far as the eye can see. Some clouds would tower so high they would cast enormous shadows onto the cloud layers below them. And if you watched long enough, you’d see that the planet’s entire atmosphere is flowing and churning.",
    "If your imaginary spacecraft zoomed higher, you’d notice that Jupiter’s globe is striped—astronomers call the lightly colored atmospheric bands “zones” and the darker parts “belts.”",
    "Jupiter’s thick atmosphere is home to countless violent, swirling storms. They come in all sizes, from small ones that form and die quickly, to huge, spinning spots that can last for months and even years! The biggest storm on Jupiter is also the most famous in all the solar system. It is called the Great Red Spot, and for good reason— it’s bigger than Earth, and its whirling orangey-red clouds have been raging for over 180 years, possibly even longer!",
    "If you look really carefully, using a good pair of binoculars, you might be able to spot Jupiter’s four largest moons—Io, Europa, Ganymede, and Callisto. The moons will look like little starlike specks close to the bright planet. As these moons travel around Jupiter they change position night by night, so occasionally all four aren’t visible from Earth at the same time. Today, we know there are at least 80 moons in total orbiting Jupiter—but there may be other tiny ones that nobody has spotted yet!",
  ],
  saturn: [
    "Encircled by a magnificent system of rings, Saturn is the second largest planet in our solar system, it’s a giant world made mostly of hydrogen and helium, perhaps with an icy and rocky core. Even though Saturn is very large, it isn’t very dense. If it were possible to build a swimming pool big enough, Saturn would float in it!",
    "At the very top of Saturn, above its north pole, lies a spectacular shape. It is a pattern of clouds called a “polar hexagon”. As the clouds move through Saturn’s polar skies, atmospheric waves guide their flow, a bit like the way a curving riverbed influences the direction of the water above it. Close-up images of the very heart of the six-sided swirl show towering storm clouds spiraling around.",
    "You could fit Earth, the moon, and Mars side by side within Saturn’s polar hexagon—with room to spare!",
    "If a fragment of Saturn’s magnificent ring system was floating in front of you right now, it would look similar to a clump of snow. Astronomers aren’t sure exactly how all these icy chunks ended up circling Saturn. One idea is that they are the remains of a moon that was crumbled into pieces by the twisting and pulling force of the giant planet’s gravity. The clumps range in size from tiny particles to boulders about the size of a tennis court!",
    "If you could get up close, you would see that the rings are made of a lot of individual streams. Some seem tightly packed together, while others have large spaces between them. Though the main group of rings around Saturn measures about 280,000km across, they’re actually incredibly thin—some are only about 10 meters deep.",
    "Saturn also has 83 moons, making it the planet with the largest known family of moons in the solar system. Some of its moons are large and spherical, and some are small potato-shaped objects that dance gracefully near the edges of the rings. Others have very strange forms indeed, such as Hyperion, which looks like a puffy sponge! Some of Saturn’s moons sculpt the path of its rings, pushing them into place with the force of their gravity.",

  ],
  uranus: [
    "Far from the warmth of the sun, Uranus moves slowly through the cold depths of space. It has a ring system and a collection of small moons, but there’s something that makes it a bit different from the other planets, it orbits(or spins) the sun on its side. One possible reason for this is that long ago, the planet was smashed into by another world.",
    "Uranus has five major moons. Its largest, Miranda, is famous for its huge cliffs— they’re several kilometers high. Uranus also has faint rings. The inner rings are narrow and dark. The outer rings are brightly colored and easier to see.",
    "No one knows for sure what lies under its thick blanket of clouds, but it could be a core of ice and rock. Uranus’s atmosphere is made of hydrogen and helium like Jupiter and Saturn, but it also has methane. The methane makes Uranus blue. ",
],
  neptune: [
    "It's difficult to imagine just how far away from the sun the planet Neptune is. But it's about 4.5 billion km away, which means that if you could drive at 80 km per hour through space, it would take you more than 6,000 years to reach it.",
    // "At this enormous distance, it takes Neptune 165 Earth years to go all the way around the sun once.",
    "Dark vortexes and bright clouds sometimes appear in Neptune's deep blue atmosphere. Fierce winds whip through the planet's thick atmosphere, which is made up of hydrogen and helium, along with other gases like methane. Neptune is made of a thick fog of water, ammonia, and methane over an Earth-sized solid center. The tremendous temperatures and pressures inside Neptune make some scientists think that diamonds could be forming and swirling through the planet's hidden depths. Imagine rain made of diamonds!",
    // {
    //     type: "image",
    //     src: "/neptune.jpg",
    //     alt: "Flat-map of Neptune",
    // }
  ]
}